// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4wbAPCSxjtXYXhg2tKi8zlBF1Qnq4GtI',
    appId: '1:635856553145:web:a3c617e29d476faf4f8768',
    messagingSenderId: '635856553145',
    projectId: 'alqasim-coaching',
    authDomain: 'alqasim-coaching.firebaseapp.com',
    storageBucket: 'alqasim-coaching.firebasestorage.app',
    measurementId: 'G-CZVFVR599L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq4H3N2TfhS5sgSkqlEbh2iHADHmjxixc',
    appId: '1:635856553145:android:266c8def90c8f39d4f8768',
    messagingSenderId: '635856553145',
    projectId: 'alqasim-coaching',
    storageBucket: 'alqasim-coaching.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA38iGK9YTD4fF2FznzoMnj9VyZaNA53Nc',
    appId: '1:635856553145:ios:a631a00438b94dd74f8768',
    messagingSenderId: '635856553145',
    projectId: 'alqasim-coaching',
    storageBucket: 'alqasim-coaching.firebasestorage.app',
    iosBundleId: 'com.oceanicgroup.qrcodescanner',
  );
}
